name: Gacha Vibes Forecast

on:
  schedule:
    - cron: "0 0 */4 * *"
  workflow_dispatch:

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Random start delay
        run: |
          delay=$((RANDOM % 120 + 30))
          echo "Sleeping for $delay seconds to avoid hitting Google at predictable times..."
          sleep $delay

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python main.py
